name: skripsi_dashcam_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.4
  get_it: ^7.2.0
  image_gallery_saver: ^2.0.3
  intl: ^0.19.0
  screenshot: ^2.1.0
  web_socket_channel: ^2.3.0
  fluttertoast: ^8.2.2
  chewie: ^1.7.4
  video_player: ^2.7.2
  get_thumbnail_video: ^0.6.1
  path_provider: ^2.1.1
  http: ^1.1.2
  wifi_iot: ^0.3.19
  ffmpeg_kit_flutter: ^6.0.3-LTS
  location: ^5.0.3

dev_dependencies:
  build_runner: null
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
    - family: Consolas
      fonts:
        - asset: assets/fonts/Consolas.ttf

  assets:
    - assets/images/
    - assets/icons/
    - assets/json/
    - assets/videos/
