name: skripsi_dashcam_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^6.2.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.4
  get_it: ^7.2.0
  image_gallery_saver: ^1.7.1
  screenshot: ^1.3.0
  web_socket_channel: ^2.3.0

dev_dependencies:

  # add build runner if not already added
  build_runner: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0

flutter:
  uses-material-design: true

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf

  assets:
    - assets/images/
    - assets/icons/
