name: skripsi_dashcam_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # For state management
  flutter_bloc: ^8.1.2
  # Our service locator
  get_it: ^7.2.0
  # Allows easier routing
  auto_route: ^6.2.0
  # Allows value based equality for our classes e.g Eat() == Eat() is true
  equatable: ^2.0.5
  # Functional programming thingies
  dartz: ^0.10.1

  # Web socket library
  web_socket_channel: ^2.3.0

  # UI
  flutter_svg: ^2.0.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  
  # add build runner if not already added
  build_runner:

flutter:
  uses-material-design: true

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf

  assets:
    - assets/images/
    - assets/icons/
