name: skripsi_dashcam_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # For state management
  flutter_bloc: ^8.1.2
  # Our service locator
  get_it: ^7.2.0
  # Generates code for us by providing annotations we can use
  injectable: ^2.1.0
  # Allows converting json to dart class and back 
  json_annotation: ^4.8.0
  # Allows easier routing
  auto_route: ^5.0.4
  # Allows value based equality for our classes e.g Eat() == Eat() is true
  equatable: ^2.0.5
  web_socket_channel: ^2.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # add the generator to your dev_dependencies
  injectable_generator:
  # add build runner if not already added
  build_runner:

flutter:
  uses-material-design: true
